In [1]:
import pandas as pd
import numpy as np

In [2]:
movies=pd.read_csv('tmdb-movie-metadata/tmdb_5000_movies.csv')

In [16]:
print (movies.head())
print (movies.shape)

      budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "nam

In [7]:
#tfidf of the overview columns
movies['overview'].fillna('NA',inplace=True)
print (movies[movies['overview'].isna()])

Empty DataFrame
Columns: [budget, genres, homepage, id, keywords, original_language, original_title, overview, popularity, production_companies, production_countries, release_date, revenue, runtime, spoken_languages, status, tagline, title, vote_average, vote_count]
Index: []


In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=1000,max_df=0.7)
X = vectorizer.fit_transform(movies['overview'])

In [14]:
print (X.toarray())
print (vectorizer.get_feature_names())
vecotrizer_df = pd.DataFrame(X.toarray(), columns = vectorizer.get_feature_names())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['000', '10', '12', '20', 'abandoned', 'about', 'accident', 'accidentally', 'across', 'act', 'action', 'actor', 'actually', 'adventure', 'adventures', 'affair', 'african', 'after', 'again', 'against', 'age', 'agent', 'aging', 'ago', 'agrees', 'alex', 'alice', 'alien', 'alive', 'all', 'alone', 'along', 'also', 'always', 'ambitious', 'america', 'american', 'among', 'an', 'ancient', 'angeles', 'animal', 'another', 'any', 'anything', 'apart', 'apartment', 'are', 'armed', 'army', 'around', 'arrives', 'art', 'artist', 'arts', 'as', 'assassin', 'assigned', 'assignment', 'assistant', 'at', 'attack', 'attempt', 'attempts', 'away', 'baby', 'back', 'bad', 'band', 'bank', 'bar', 'based', 'basketball', 'battle', 'be', 'beautiful', 'beauty', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'befriends', 'begin', 'begins', 'behind', 'b

In [15]:
print (vecotrizer_df)

      000   10   12        20  abandoned     about  accident  accidentally  \
0     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
1     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
2     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
3     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
4     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
5     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
6     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
7     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
8     0.0  0.0  0.0  0.000000   0.000000  0.163751       0.0      0.000000   
9     0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0      0.000000   
10    0.0  0.0  0.0  0.000000   0.251317  0.000000       0.0      0.000000   
11    0.0  0.0  0.0  0.000000   0.000000  0.000000       0.0    

In [19]:
merged_df = pd.concat([movies[['original_title','genres']],vecotrizer_df], axis=1)

In [20]:
print (merged_df)

                                   original_title  \
0                                          Avatar   
1        Pirates of the Caribbean: At World's End   
2                                         Spectre   
3                           The Dark Knight Rises   
4                                     John Carter   
5                                    Spider-Man 3   
6                                         Tangled   
7                         Avengers: Age of Ultron   
8          Harry Potter and the Half-Blood Prince   
9              Batman v Superman: Dawn of Justice   
10                               Superman Returns   
11                              Quantum of Solace   
12     Pirates of the Caribbean: Dead Man's Chest   
13                                The Lone Ranger   
14                                   Man of Steel   
15       The Chronicles of Narnia: Prince Caspian   
16                                   The Avengers   
17    Pirates of the Caribbean: On Stranger Ti

In [ ]:
#First lets dummyfy the genres
merged_df['genre_list']= merged_df['genres']